### ISSUE TITLE
User Language

### ISSUE THREAD

**Issue by Jurgen8en** [Setono/google-analytics-measurement-protocol#27]
Add to hitbuilder:
- User Language https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters?hl=nl#ul
- Screen Resolution

It is missing in my reports....

**Comment by loevgaard** [comment]
The parameters has been added to the `HitBuilderInterface`. For the user language a help has been made to make it easy to populate. This needs to be implemented in packages down stream :)

**Comment by Jurgen8en** [comment]
Thanks, any updates about "screen resolution" ?

**Comment by loevgaard** [comment]
Screen resolution is not something I have prioritized atm. Mostly because it's a client side thing, so to add screen resolution I would have to have logic handling ajax requests, updating earlier hits etc.

Your best bet is probably to implement it yourself (https://www.w3schools.com/howto/howto_js_get_current_window.asp). At least for now :)

**Comment by loevgaard** [comment]
Oh, will just reopen to have this issue as a reminder :)

**Comment by loevgaard** [comment]
Closing this as current development is focused on GA4 :)
